### ISSUE TITLE
LeetCode 146 wrong answer

### ISSUE THREAD

**Issue by zhuliwen** [qiyuangong/leetcode#40]
I have tried the solution of [Leetcode 146](https://github.com/qiyuangong/leetcode/blob/master/python/146_LRU_Cache.py), and it shows wrong answer?

**Comment by qiyuangong** [comment]
Thank you for providing this feedback. Yes, this solution produce wrong answer.
It is fixed by 056459464f15df885538aa90f6db882a2f4dbd20 . Pls try agin. :)

**Comment by zhuliwen** [comment]
thanks
