### ISSUE TITLE
`TypeError` in Q12 Integer to Roman 

### ISSUE THREAD

**Issue by lowspace** [qiyuangong/leetcode#41]
TypeError: 'float' object cannot be interpreted as an integer

https://github.com/qiyuangong/leetcode/blob/056459464f15df885538aa90f6db882a2f4dbd20/python/012_Integer_to_Roman.py#L38

**Comment by lowspace** [comment]
To correct this error, try `for j in range(int(k)):`.

**Comment by qiyuangong** [comment]
Thank you @lowspace !
That's my fault. My previous solution is for Python2, in Python3 it will raise TypeError.

Have change to Python3 :)

Issue closed
