### ISSUE TITLE
Add a new repo in  Other leetcode solutions link. 

### ISSUE THREAD

**Issue by anishLearnsToCode** [qiyuangong/leetcode#44]
Could you please also add my LeetCode solutions repo in the _other leetcode_ section.

Have a look at it over here: [leetcode-algorithms](https://github.com/anishLearnsToCode/leetcode-algorithms)

It contains solutions in java and python and also video descriptions of the algorithm.

**Comment by qiyuangong** [comment]
> Could you please also add my LeetCode solutions repo in the _other leetcode_ section.
> 
> Have a look at it over here: [leetcode-algorithms](https://github.com/anishLearnsToCode/leetcode-algorithms)
> 
> It contains solutions in java and python and also video descriptions of the algorithm.

I took a look at your repo. Nice repo indeede. 👍 

I think you can make a pull request on README.md. I will merge it when it is ready.

**Comment by anishLearnsToCode** [comment]
Thanks. Will do.

**Comment by anishLearnsToCode** [comment]
Created the PR, see: https://github.com/qiyuangong/leetcode/pull/45

**Comment by qiyuangong** [comment]
PR merged. Thank you for your contribution!
Issue closed.
