### ISSUE TITLE
Wrong answer in Problem Q7 and Test case code in "__main__"

### ISSUE THREAD

**Issue by LONGNEW** [qiyuangong/leetcode#73]
Hi, I just check a code for  Q7. [Reverse Integer](https://leetcode.com/problems/reverse-integer/) and it gives wrong answer in the test case.

So, Can I make some changes in this code?

And, In old codes there are some test case code in __main__.
Can I update this code by erasing?

**Comment by qiyuangong** [comment]
> Hi, I just check a code for Q7. [Reverse Integer](https://leetcode.com/problems/reverse-integer/) and it gives wrong answer in the test case.
> 
> So, Can I make some changes in this code?
> 
> And, In old codes there are some test case code in **main**. Can I update this code by erasing?

Of course, you can. You can modify any code if they are not correct.
