### ISSUE TITLE
Add Bitwise solution for Python 007_Reverse_Integer.py

### ISSUE THREAD

**Issue by ROMEEZHOU** [qiyuangong/leetcode#79]
Hi, I noticed that the current solution for 007_Reverse_Integer.py is using string. I am wondering if it is possible that we also add a bitwise method (basically checking if the last bit is 1, and shift the binary string << 1 every time), which could be more proper here. I can add this method if that is ok.

**Comment by qiyuangong** [comment]
Of course. You can create a PR for this new method. :)

**Comment by qiyuangong** [comment]
Issue addressed by @ROMEEZHOU in #80 

Thank you for your contribution! :)

**Comment by ROMEEZHOU** [comment]
Glad to help! This is a really helpful Repo!
